---

# https://github.com/SeleniumHQ/docker-selenium
- name: bring up selenium grid hub
  become: yes
  docker_compose:
    project_name: "seleniumgrid"
    definition:
      version: '2'
      services:
        hub:
          image: "selenium/hub:{{ docker_selenium_grid_hub_version }}"
          container_name: "hub"
          ports:
            - "4442:4442"
            - "4443:4443"
            - "4444:4444"
          volumes:
            - /dev/shm:/dev/shm
          restart: always

- name: restart the os
  become: yes
  ansible.builtin.reboot:
  when: docker_selenium_grid_hub_restart_always == true
